
-- TABLE meals
-- Breakfast
INSERT INTO meals (meal_name, duration, image, meal_type, description, ingredients, directions) 
VALUES ('Greek Yogurt Parfait', 10, 'https://plus.unsplash.com/premium_photo-1669680785558-c189b49aed4e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2787&q=80', 'Breakfast', 'A nutritious breakfast parfait with Greek yogurt, fresh berries, and granola.', 'Greek yogurt, fresh berries, granola', '1. In a serving glass or bowl, layer Greek yogurt, fresh berries, and granola. 2. Repeat the layers as desired. 3. Serve immediately and enjoy!');
INSERT INTO meals (meal_name, duration, image, meal_type, description, ingredients, directions) 
VALUES ('Oatmeal with Almonds and Banana', 15, 'https://images.unsplash.com/photo-1541809570-cce873416d94?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2874&q=80', 'Breakfast', 'Heart-healthy oatmeal topped with sliced almonds and ripe bananas.', 'Oatmeal, sliced almonds, ripe bananas', '1. Cook the oatmeal according to package instructions. 2. Top the cooked oatmeal with sliced almonds and ripe bananas. 3. Serve hot and enjoy!');
INSERT INTO meals (meal_name, duration, image, meal_type, description, ingredients, directions) 
VALUES ('Egg and Spinach Breakfast Wrap', 20, 'https://images.unsplash.com/photo-1667499707432-0524fcfb63ba?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2823&q=80', 'Breakfast', 'A protein-packed breakfast wrap with scrambled eggs and fresh spinach.', 'Eggs, spinach, tortilla wraps', '1. In a skillet, scramble the eggs and cook the spinach until wilted. 2. Warm the tortilla wraps in a separate skillet. 3. Fill the wraps with the scrambled eggs and spinach. 4. Roll up the wraps and serve hot.');

-- Lunch
INSERT INTO meals (meal_name, duration, image, meal_type, description, ingredients, directions) 
VALUES ('Quinoa Salad with Chickpeas', 20, 'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2864&q=80', 'Lunch', 'A satisfying quinoa salad with chickpeas, cucumbers, and a lemon tahini dressing.', 'Quinoa, chickpeas, cucumbers, lemon tahini dressing', '1. Cook quinoa according to package instructions and let it cool. 2. In a large bowl, combine quinoa, chickpeas, and diced cucumbers. 3. Drizzle with lemon tahini dressing and toss to combine. 4. Serve chilled and enjoy!');
INSERT INTO meals (meal_name, duration, image, meal_type, description, ingredients, directions) 
VALUES ('Grilled Chicken Caesar Salad', 15, 'https://images.unsplash.com/photo-1582034986517-30d163aa1da9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2960&q=80', 'Lunch', 'A classic Caesar salad with grilled chicken breast and homemade dressing.', 'Grilled chicken breast, romaine lettuce, Caesar dressing', '1. Grill the chicken breast until fully cooked and slice it. 2. In a large bowl, toss romaine lettuce with Caesar dressing. 3. Top the salad with grilled chicken slices. 4. Serve immediately and enjoy!');
INSERT INTO meals (meal_name, duration, image, meal_type, description, ingredients, directions) 
VALUES ('Avocado and Turkey Wrap', 10, 'https://img.freepik.com/free-photo/shawarma-from-juicy-beef-lettuce-tomatoes-cucumbers-paprika-onion-pita-bread-with-spinach-diet-menu_2829-14466.jpg?w=1480&t=st=1694270898~exp=1694271498~hmac=0d8f869a5ca48e65d96432dba0a2b7b1f55ac7fd6d129ad183f6ef903a2ebcd8', 'Lunch', 'A flavorful wrap with sliced avocado, turkey, and a light mayo spread.', 'Sliced avocado, turkey slices, light mayo, tortilla wraps', '1. Lay out a tortilla wrap and spread a thin layer of light mayo. 2. Place turkey slices and sliced avocado on top. 3. Roll up the wrap and serve.');

-- Dinner
INSERT INTO meals (meal_name, duration, image, meal_type, description, ingredients, directions)  
VALUES ('Salmon with Quinoa and Asparagus', 25, 'https://img.freepik.com/premium-photo/salmon-fillet-grilled-with-bulgur-green-beans-healthy-food-diet-top-view_745171-1404.jpg?w=740', 'Dinner', 'Baked salmon served with quinoa and roasted asparagus.', 'Salmon fillet, quinoa, asparagus', '1. Season the salmon fillet and bake it in the oven until cooked through. 2. Cook quinoa according to package instructions. 3. Roast asparagus until tender. 4. Serve the baked salmon with quinoa and roasted asparagus.');
INSERT INTO meals (meal_name, duration, image, meal_type, description, ingredients, directions) 
VALUES ('Mediterranean Stuffed Bell Peppers', 30, 'https://img.freepik.com/free-photo/peppers-stuffed-with-potatoes-chorizo_2829-11221.jpg?w=900&t=st=1694271058~exp=1694271658~hmac=12ac78f9826465140e785a48a39ab8392570df685d5317b015061b3fbbc07d05', 'Dinner', 'Bell peppers filled with a Mediterranean-inspired mixture of rice, vegetables, and herbs.', 'Bell peppers, rice, vegetables, herbs', '1. Cut the tops off the bell peppers and remove the seeds. 2. In a bowl, mix cooked rice, diced vegetables, and herbs. 3. Stuff the bell peppers with the rice mixture. 4. Bake in the oven until the peppers are tender.');
INSERT INTO meals (meal_name, duration, image, meal_type, description, ingredients, directions) 
VALUES ('Grilled Vegetable and Tofu Stir-Fry', 20, 'https://img.freepik.com/free-photo/top-view-high-protein-meal-assortment_23-2149089637.jpg?w=1480&t=st=1694271169~exp=1694271769~hmac=49da894b35661d95a4cd6321b57ab2dc10bbce268222e1318df62cb4721d3035', 'Dinner', 'Stir-fried tofu and a variety of vegetables in a savory sauce.', 'Tofu, mixed vegetables, stir-fry sauce', '1. Cut tofu into cubes and stir-fry in a pan until lightly browned. 2. Add mixed vegetables to the pan and stir-fry until tender. 3. Pour stir-fry sauce over the tofu and vegetables. 4. Serve hot.');

-- Snacks
INSERT INTO meals (meal_name, duration, image, meal_type, description, ingredients, directions) 
VALUES ('Hummus and Veggie Platter', 10, 'https://img.freepik.com/free-photo/top-view-hummus-with-assortment-vegetables_23-2148562749.jpg?w=1480&t=st=1694271200~exp=1694271800~hmac=8079f401974bb66b61f652ee78561462c3adee6208e375546fc42110d77f0274', 'Snack', 'A healthy snack platter featuring hummus and fresh-cut vegetables.', 'Hummus, assorted vegetables (e.g., carrots, cucumbers, bell peppers)', '1. Arrange the assorted vegetables on a platter. 2. Serve with a bowl of hummus for dipping.');
INSERT INTO meals (meal_name, duration, image, meal_type, description, ingredients, directions) 
VALUES ('Mixed Berry Smoothie', 5, 'https://img.freepik.com/free-photo/high-angle-glasses-with-smoothie_23-2148751825.jpg?w=826&t=st=1694271227~exp=1694271827~hmac=88eb85b0659b53d108e9fe19eea2f5c98f6646155d7ed4ae82186fdc24ac732b', 'Snack', 'A refreshing smoothie made with mixed berries, yogurt, and honey.', 'Mixed berries, yogurt, honey', '1. Blend mixed berries, yogurt, and honey until smooth. 2. Pour into a glass and enjoy!');
INSERT INTO meals (meal_name, duration, image, meal_type, description, ingredients, directions) 
VALUES ('Almonds and Dried Fruits', 5, 'https://img.freepik.com/free-photo/top-view-mix-nuts-walnuts-raisins-peanuts-almonds_141793-4087.jpg?w=1480&t=st=1694271259~exp=1694271859~hmac=54f04efe690b67183117bd71cafa92323026db20f54d7595fc47471e1c47f3ab', 'Snack', 'A satisfying snack of almonds and a variety of dried fruits.', 'Almonds, dried fruits (e.g., raisins, peanuts)', '1. Combine almonds and dried fruits in a bowl. 2. Enjoy as a snack.');
